import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const b64 = (p: string) => readFileSync(p).toString('base64');

const assets = {
  JOST_400: b64(join(root, 'node_modules/@fontsource/jost/files/jost-latin-400-normal.woff2')),
  JOST_600: b64(join(root, 'node_modules/@fontsource/jost/files/jost-latin-600-normal.woff2')),
  ROBOTO_400: b64(join(root, 'node_modules/@fontsource/roboto/files/roboto-latin-400-normal.woff2')),
  ROBOTO_500: b64(join(root, 'node_modules/@fontsource/roboto/files/roboto-latin-500-normal.woff2')),
  NI_LOGO_PNG: b64(join(root, 'src/assets/ni-logo.png')),
};

const body = Object.entries(assets)
  .map(([k, v]) => `export const ${k} = '${v}';`)
  .join('\n');

writeFileSync(
  join(root, 'src/render/assets.generated.ts'),
  `// AUTO-GENERATED by scripts/gen-render-assets.ts. Do not edit by hand.\n${body}\n`,
);
console.log('Wrote src/render/assets.generated.ts');
