import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const b64 = (p: string) => readFileSync(p).toString('base64');
const txt = (p: string) => readFileSync(p, 'utf8');
const ds = (f: string) => join(root, 'src/render/design-system', f);
const font = (p: string) => b64(join(root, p));

const constants: Record<string, string> = {
  JOST_300: font('node_modules/@fontsource/jost/files/jost-latin-300-normal.woff2'),
  JOST_400: font('node_modules/@fontsource/jost/files/jost-latin-400-normal.woff2'),
  JOST_500: font('node_modules/@fontsource/jost/files/jost-latin-500-normal.woff2'),
  JOST_600: font('node_modules/@fontsource/jost/files/jost-latin-600-normal.woff2'),
  JOST_700: font('node_modules/@fontsource/jost/files/jost-latin-700-normal.woff2'),
  ROBOTO_300: font('node_modules/@fontsource/roboto/files/roboto-latin-300-normal.woff2'),
  ROBOTO_400: font('node_modules/@fontsource/roboto/files/roboto-latin-400-normal.woff2'),
  ROBOTO_500: font('node_modules/@fontsource/roboto/files/roboto-latin-500-normal.woff2'),
  ROBOTO_700: font('node_modules/@fontsource/roboto/files/roboto-latin-700-normal.woff2'),
  MONO_400: font('node_modules/@fontsource/jetbrains-mono/files/jetbrains-mono-latin-400-normal.woff2'),
  MONO_500: font('node_modules/@fontsource/jetbrains-mono/files/jetbrains-mono-latin-500-normal.woff2'),
  COLORS_CSS: txt(ds('colors_and_type.css')),
  DECK_CSS: txt(ds('deck.css')),
  PROPOSAL_CSS: txt(ds('proposal.css')),
  DECK_STAGE_JS: txt(ds('deck-stage.js')),
  LUCIDE_JS: txt(ds('lucide.min.js')),
  LOGO_MARK_SVG: txt(ds('logo-mark.svg')),
  LOGO_WORDMARK_SVG: txt(ds('logo-wordmark.svg')),
};

const esc = (s: string) => '`' + s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${') + '`';
const body = Object.entries(constants).map(([k, v]) => `export const ${k} = ${esc(v)};`).join('\n');
writeFileSync(join(root, 'src/render/assets.generated.ts'),
  `// AUTO-GENERATED by scripts/gen-render-assets.ts. Do not edit by hand.\n${body}\n`);
console.log('Wrote src/render/assets.generated.ts');
